version: '3.4'

services:
  gapindiaorg:
    image: gapindiaorg
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
